name: Build & Deploy Astro

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Build the project
        run: npm run build

      - name: SSH auth & known_hosts
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.VPS_PORT }}" "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync dist/ to VPS (overwrite, delete stale)
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.VPS_PORT }}" \
            "dist/" \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_PATH }}/"

      - name: Reload Nginx
        run: |
          ssh -p "${{ secrets.VPS_PORT }}" \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" \
            "sudo systemctl reload nginx"
