name: Build & Deploy Astro

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Build the project
        run: |
          npm ci 
          npm run build

      - name: SSH auth
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/ci_key
          chmod 600 ~/.ssh/ci_key
          ssh-keyscan -p "${{ secrets.PORT }}" "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/ci_key -p ${{ secrets.PORT }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes" \
            dist/ \
            "${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_PATH }}/"
